[advisories]
unmaintained = "none"
yanked = "warn"

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Unicode-DFS-2016",
]
copyleft = "warn"
allow-osi-fsf-free = true
confidence-threshold = 0.7

[bans]
multiple-versions = "warn"
wildcards = "warn"
