// @ts-nocheck
/**
 * Generate contracts/opaque-poseidon/src/constants.rs — the BN254 scalar-field
 * Montgomery constants and the circomlib Poseidon round constants (C) + MDS
 * matrices (M) for arity 2 (t=3) and arity 3 (t=4), the only arities the
 * privacy-pool contract needs (Poseidon(2) for label + Merkle nodes,
 * Poseidon(3) for the deposit commitment).
 *
 * Everything is machine-derived so there are no hand-transcribed magic numbers:
 *   - The field constants (MODULUS, INV, R2) are computed from r with BigInt.
 *   - C and M are read verbatim from circomlibjs' poseidon_constants.json (the
 *     same canonical Hades parameters circom's poseidon.circom and the scanner's
 *     poseidon-bn128 use), reduced mod r, and pre-converted to Montgomery form
 *     (c·R mod r) so the on-chain permutation runs entirely in the Montgomery
 *     domain with no per-constant conversion.
 *
 * The Rust unit tests assert the resulting hashes match circomlibjs vectors, so
 * any error in these constants (or in the field code) fails loudly.
 *
 * Usage: tsx scripts/gen-poseidon-constants.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

// circomlibjs ships the canonical constants under src/. Either workspace copy works.
const CONSTANTS_JSON = resolve(
  ROOT,
  "frontend/node_modules/circomlibjs/src/poseidon_constants.json",
);

// BN254 scalar field order r (== SCALAR_FIELD in groth16-verifier).
const R =
  21888242871839275222246405745257275088548364400416034343698204186575808495617n;
const TWO64 = 1n << 64n;
const RMONT = (1n << 256n) % R; // R (the Montgomery radix) mod r
const R2 = (RMONT * RMONT) % R; // R^2 mod r, used to lift inputs into Montgomery form

// Round numbers, from poseidon_reference.js (N_ROUNDS_F=8; N_ROUNDS_P per t-2).
const N_ROUNDS_F = 8;
const N_ROUNDS_P = [56, 57, 56, 60, 60, 63, 64, 63, 60, 66, 60, 65, 70, 60, 64, 68];

function modinv(a: bigint, m: bigint): bigint {
  let [old_r, r] = [((a % m) + m) % m, m];
  let [old_s, s] = [1n, 0n];
  while (r !== 0n) {
    const q = old_r / r;
    [old_r, r] = [r, old_r - q * r];
    [old_s, s] = [s, old_s - q * s];
  }
  return ((old_s % m) + m) % m;
}

// INV = -r^{-1} mod 2^64 (the CIOS Montgomery constant).
const INV = (TWO64 - modinv(R % TWO64, TWO64)) % TWO64;

function toMont(x: bigint): bigint {
  return (((x % R) + R) % R) * RMONT % R;
}

/** bigint -> four little-endian u64 limbs as `0x..u64` literals. */
function limbsLE(v: bigint): string[] {
  const out: string[] = [];
  let n = v;
  for (let i = 0; i < 4; i++) {
    out.push(`0x${(n & (TWO64 - 1n)).toString(16).padStart(16, "0")}`);
    n >>= 64n;
  }
  return out;
}

function fr(v: bigint): string {
  return `Fr([${limbsLE(v).join(", ")}])`;
}

function emitC(name: string, c: bigint[]): string {
  const body = c.map((x) => `    ${fr(toMont(x))},`).join("\n");
  return `pub const ${name}: [Fr; ${c.length}] = [\n${body}\n];`;
}

function emitM(name: string, m: bigint[][]): string {
  const rows = m
    .map((row) => `    [${row.map((x) => fr(toMont(x))).join(", ")}]`)
    .join(",\n");
  return `pub const ${name}: [[Fr; ${m.length}]; ${m.length}] = [\n${rows},\n];`;
}

function main() {
  const consts = JSON.parse(readFileSync(CONSTANTS_JSON, "utf8"));
  // poseidon_constants.json: { C: [...per t-2...], M: [...per t-2...] }
  // index 1 => t=3 (arity 2); index 2 => t=4 (arity 3).
  const C = consts.C as string[][];
  const M = consts.M as string[][][];

  const c3 = C[1].map((s) => BigInt(s));
  const m3 = M[1].map((row) => row.map((s) => BigInt(s)));
  const c4 = C[2].map((s) => BigInt(s));
  const m4 = M[2].map((row) => row.map((s) => BigInt(s)));

  // Sanity: lengths must match (N_ROUNDS_F + N_ROUNDS_P[t-2]) * t.
  const expLen = (t: number) => (N_ROUNDS_F + N_ROUNDS_P[t - 2]) * t;
  if (c3.length !== expLen(3)) throw new Error(`C t=3 len ${c3.length} != ${expLen(3)}`);
  if (c4.length !== expLen(4)) throw new Error(`C t=4 len ${c4.length} != ${expLen(4)}`);
  if (m3.length !== 3 || m3[0].length !== 3) throw new Error("M t=3 not 3x3");
  if (m4.length !== 4 || m4[0].length !== 4) throw new Error("M t=4 not 4x4");

  const header = `// @generated by scripts/gen-poseidon-constants.ts — DO NOT EDIT BY HAND.
//
// BN254 scalar-field Montgomery constants + circomlib Poseidon parameters for
// arity 2 (t=3) and arity 3 (t=4). C/M are pre-converted to Montgomery form
// (c·R mod r). Regenerate with: tsx scripts/gen-poseidon-constants.ts
use crate::field::Fr;

/// BN254 scalar field modulus r, little-endian u64 limbs.
pub const MODULUS: [u64; 4] = [
    ${limbsLE(R).join(", ")},
];

/// -r^{-1} mod 2^64 (CIOS Montgomery constant).
pub const INV: u64 = ${`0x${INV.toString(16).padStart(16, "0")}`};

/// R^2 mod r (radix R = 2^256), used to lift a standard integer into Montgomery form.
pub const R2: Fr = ${fr(R2)};

/// Full rounds (split half at the start, half at the end).
pub const N_ROUNDS_F: usize = ${N_ROUNDS_F};
/// Partial rounds for t=3 (arity 2) and t=4 (arity 3).
pub const N_ROUNDS_P_T3: usize = ${N_ROUNDS_P[1]};
pub const N_ROUNDS_P_T4: usize = ${N_ROUNDS_P[2]};

${emitC("C_T3", c3)}

${emitM("M_T3", m3)}

${emitC("C_T4", c4)}

${emitM("M_T4", m4)}
`;

  const out = resolve(ROOT, "contracts/opaque-poseidon/src/constants.rs");
  writeFileSync(out, header);
  console.log(`Wrote ${out}`);
  console.log(`  MODULUS limbs: ${limbsLE(R).join(", ")}`);
  console.log(`  INV: 0x${INV.toString(16)}`);
  console.log(`  C_T3 ${c3.length}, M_T3 3x3, C_T4 ${c4.length}, M_T4 4x4`);
}

main();
